source 'https://rubygems.org'

gem 'byebug'
gem 'factory_bot_rails', '~> 4.11'
gem 'pry', '~> 0.13.1'
gem 'rspec', '~> 3.10'
gem 'rspec-rails', '~> 6'
gem 'rubocop', '~> 1.0', require: false
gem 'solargraph'
gem 'terminal-table'
